/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2019 Red Hat, Inc.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/machine-remediation-operator/pkg/apis/machineremediation/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// Fakemachineremediations implements machineremediationInterface
type Fakemachineremediations struct {
	Fake *FakemachineremediationV1alpha1
	ns   string
}

var machineremediationsResource = schema.GroupVersionResource{Group: "machineremediation.openshift.io", Version: "v1alpha1", Resource: "machineremediations"}

var machineremediationsKind = schema.GroupVersionKind{Group: "machineremediation.openshift.io", Version: "v1alpha1", Kind: "machineremediation"}

// Get takes name of the machineremediation, and returns the corresponding machineremediation object, and an error if there is any.
func (c *Fakemachineremediations) Get(name string, options v1.GetOptions) (result *v1alpha1.machineremediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machineremediationsResource, c.ns, name), &v1alpha1.machineremediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.machineremediation), err
}

// List takes label and field selectors, and returns the list of machineremediations that match those selectors.
func (c *Fakemachineremediations) List(opts v1.ListOptions) (result *v1alpha1.machineremediationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machineremediationsResource, machineremediationsKind, c.ns, opts), &v1alpha1.machineremediationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.machineremediationList{ListMeta: obj.(*v1alpha1.machineremediationList).ListMeta}
	for _, item := range obj.(*v1alpha1.machineremediationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineremediations.
func (c *Fakemachineremediations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machineremediationsResource, c.ns, opts))

}

// Create takes the representation of a machineremediation and creates it.  Returns the server's representation of the machineremediation, and an error, if there is any.
func (c *Fakemachineremediations) Create(machineremediation *v1alpha1.machineremediation) (result *v1alpha1.machineremediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machineremediationsResource, c.ns, machineremediation), &v1alpha1.machineremediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.machineremediation), err
}

// Update takes the representation of a machineremediation and updates it. Returns the server's representation of the machineremediation, and an error, if there is any.
func (c *Fakemachineremediations) Update(machineremediation *v1alpha1.machineremediation) (result *v1alpha1.machineremediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machineremediationsResource, c.ns, machineremediation), &v1alpha1.machineremediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.machineremediation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *Fakemachineremediations) UpdateStatus(machineremediation *v1alpha1.machineremediation) (*v1alpha1.machineremediation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(machineremediationsResource, "status", c.ns, machineremediation), &v1alpha1.machineremediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.machineremediation), err
}

// Delete takes name of the machineremediation and deletes it. Returns an error if one occurs.
func (c *Fakemachineremediations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machineremediationsResource, c.ns, name), &v1alpha1.machineremediation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *Fakemachineremediations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machineremediationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.machineremediationList{})
	return err
}

// Patch applies the patch and returns the patched machineremediation.
func (c *Fakemachineremediations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.machineremediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machineremediationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.machineremediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.machineremediation), err
}
