container_images="cmd/machine-disruption-budget cmd/machine-health-check cmd/machine-remediation cmd/machine-remediation-operator"
container_prefix=${CONTAINER_PREFIX:-index.docker.io/kubevirt}
container_tag=${CONTAINER_TAG:-latest}
image_pull_policy=${IMAGE_PULL_POLICY:-IfNotPresent}
csv_version=${CSV_VERSION:-0.0.0}
csv_previous_version=${CSV_PREVIOUS_VERSION:-0.0.0}
kubevirtci_git_hash="626ef1522fcd2a541a00613fc8c48f3efa7bf072"
namespace=openshift-machine-api
verbosity=${VERBOSITY:-2}
