/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2018 Red Hat, Inc.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubevirt.io/node-recovery/pkg/apis/noderecovery/v1alpha1"
)

// FakeNodeRemediations implements NodeRemediationInterface
type FakeNodeRemediations struct {
	Fake *FakeNoderecoveryV1alpha1
	ns   string
}

var noderemediationsResource = schema.GroupVersionResource{Group: "noderecovery.kubevirt.io", Version: "v1alpha1", Resource: "noderemediations"}

var noderemediationsKind = schema.GroupVersionKind{Group: "noderecovery.kubevirt.io", Version: "v1alpha1", Kind: "NodeRemediation"}

// Get takes name of the nodeRemediation, and returns the corresponding nodeRemediation object, and an error if there is any.
func (c *FakeNodeRemediations) Get(name string, options v1.GetOptions) (result *v1alpha1.NodeRemediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(noderemediationsResource, c.ns, name), &v1alpha1.NodeRemediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeRemediation), err
}

// List takes label and field selectors, and returns the list of NodeRemediations that match those selectors.
func (c *FakeNodeRemediations) List(opts v1.ListOptions) (result *v1alpha1.NodeRemediationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(noderemediationsResource, noderemediationsKind, c.ns, opts), &v1alpha1.NodeRemediationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeRemediationList{ListMeta: obj.(*v1alpha1.NodeRemediationList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeRemediationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeRemediations.
func (c *FakeNodeRemediations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(noderemediationsResource, c.ns, opts))

}

// Create takes the representation of a nodeRemediation and creates it.  Returns the server's representation of the nodeRemediation, and an error, if there is any.
func (c *FakeNodeRemediations) Create(nodeRemediation *v1alpha1.NodeRemediation) (result *v1alpha1.NodeRemediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(noderemediationsResource, c.ns, nodeRemediation), &v1alpha1.NodeRemediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeRemediation), err
}

// Update takes the representation of a nodeRemediation and updates it. Returns the server's representation of the nodeRemediation, and an error, if there is any.
func (c *FakeNodeRemediations) Update(nodeRemediation *v1alpha1.NodeRemediation) (result *v1alpha1.NodeRemediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(noderemediationsResource, c.ns, nodeRemediation), &v1alpha1.NodeRemediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeRemediation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeRemediations) UpdateStatus(nodeRemediation *v1alpha1.NodeRemediation) (*v1alpha1.NodeRemediation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(noderemediationsResource, "status", c.ns, nodeRemediation), &v1alpha1.NodeRemediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeRemediation), err
}

// Delete takes name of the nodeRemediation and deletes it. Returns an error if one occurs.
func (c *FakeNodeRemediations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(noderemediationsResource, c.ns, name), &v1alpha1.NodeRemediation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeRemediations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(noderemediationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeRemediationList{})
	return err
}

// Patch applies the patch and returns the patched nodeRemediation.
func (c *FakeNodeRemediations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeRemediation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(noderemediationsResource, c.ns, name, data, subresources...), &v1alpha1.NodeRemediation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeRemediation), err
}
