/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2019 Red Hat, Inc.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/openshift/machine-remediation-operator/pkg/apis/machineremediation/v1alpha1"
	scheme "github.com/openshift/machine-remediation-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// machineremediationsGetter has a method to return a machineremediationInterface.
// A group's client should implement this interface.
type machineremediationsGetter interface {
	machineremediations(namespace string) machineremediationInterface
}

// machineremediationInterface has methods to work with machineremediation resources.
type machineremediationInterface interface {
	Create(*v1alpha1.machineremediation) (*v1alpha1.machineremediation, error)
	Update(*v1alpha1.machineremediation) (*v1alpha1.machineremediation, error)
	UpdateStatus(*v1alpha1.machineremediation) (*v1alpha1.machineremediation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.machineremediation, error)
	List(opts v1.ListOptions) (*v1alpha1.machineremediationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.machineremediation, err error)
	machineremediationExpansion
}

// machineremediations implements machineremediationInterface
type machineremediations struct {
	client rest.Interface
	ns     string
}

// newmachineremediations returns a machineremediations
func newmachineremediations(c *machineremediationV1alpha1Client, namespace string) *machineremediations {
	return &machineremediations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineremediation, and returns the corresponding machineremediation object, and an error if there is any.
func (c *machineremediations) Get(name string, options v1.GetOptions) (result *v1alpha1.machineremediation, err error) {
	result = &v1alpha1.machineremediation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machineremediations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of machineremediations that match those selectors.
func (c *machineremediations) List(opts v1.ListOptions) (result *v1alpha1.machineremediationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.machineremediationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machineremediations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineremediations.
func (c *machineremediations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machineremediations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineremediation and creates it.  Returns the server's representation of the machineremediation, and an error, if there is any.
func (c *machineremediations) Create(machineremediation *v1alpha1.machineremediation) (result *v1alpha1.machineremediation, err error) {
	result = &v1alpha1.machineremediation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machineremediations").
		Body(machineremediation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineremediation and updates it. Returns the server's representation of the machineremediation, and an error, if there is any.
func (c *machineremediations) Update(machineremediation *v1alpha1.machineremediation) (result *v1alpha1.machineremediation, err error) {
	result = &v1alpha1.machineremediation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machineremediations").
		Name(machineremediation.Name).
		Body(machineremediation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *machineremediations) UpdateStatus(machineremediation *v1alpha1.machineremediation) (result *v1alpha1.machineremediation, err error) {
	result = &v1alpha1.machineremediation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machineremediations").
		Name(machineremediation.Name).
		SubResource("status").
		Body(machineremediation).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineremediation and deletes it. Returns an error if one occurs.
func (c *machineremediations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machineremediations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineremediations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machineremediations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineremediation.
func (c *machineremediations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.machineremediation, err error) {
	result = &v1alpha1.machineremediation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machineremediations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
