/*
 * This file is part of the KubeVirt project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright 2018 Red Hat, Inc.
 *
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubevirt.io/node-recovery/pkg/apis/noderecovery/v1alpha1"
	scheme "kubevirt.io/node-recovery/pkg/client/clientset/versioned/scheme"
)

// NodeRemediationsGetter has a method to return a NodeRemediationInterface.
// A group's client should implement this interface.
type NodeRemediationsGetter interface {
	NodeRemediations() NodeRemediationInterface
}

// NodeRemediationInterface has methods to work with NodeRemediation resources.
type NodeRemediationInterface interface {
	Create(*v1alpha1.NodeRemediation) (*v1alpha1.NodeRemediation, error)
	Update(*v1alpha1.NodeRemediation) (*v1alpha1.NodeRemediation, error)
	UpdateStatus(*v1alpha1.NodeRemediation) (*v1alpha1.NodeRemediation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.NodeRemediation, error)
	List(opts v1.ListOptions) (*v1alpha1.NodeRemediationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeRemediation, err error)
	NodeRemediationExpansion
}

// nodeRemediations implements NodeRemediationInterface
type nodeRemediations struct {
	client rest.Interface
}

// newNodeRemediations returns a NodeRemediations
func newNodeRemediations(c *NoderecoveryV1alpha1Client) *nodeRemediations {
	return &nodeRemediations{
		client: c.RESTClient(),
	}
}

// Get takes name of the nodeRemediation, and returns the corresponding nodeRemediation object, and an error if there is any.
func (c *nodeRemediations) Get(name string, options v1.GetOptions) (result *v1alpha1.NodeRemediation, err error) {
	result = &v1alpha1.NodeRemediation{}
	err = c.client.Get().
		Resource("noderemediations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeRemediations that match those selectors.
func (c *nodeRemediations) List(opts v1.ListOptions) (result *v1alpha1.NodeRemediationList, err error) {
	result = &v1alpha1.NodeRemediationList{}
	err = c.client.Get().
		Resource("noderemediations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeRemediations.
func (c *nodeRemediations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("noderemediations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a nodeRemediation and creates it.  Returns the server's representation of the nodeRemediation, and an error, if there is any.
func (c *nodeRemediations) Create(nodeRemediation *v1alpha1.NodeRemediation) (result *v1alpha1.NodeRemediation, err error) {
	result = &v1alpha1.NodeRemediation{}
	err = c.client.Post().
		Resource("noderemediations").
		Body(nodeRemediation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeRemediation and updates it. Returns the server's representation of the nodeRemediation, and an error, if there is any.
func (c *nodeRemediations) Update(nodeRemediation *v1alpha1.NodeRemediation) (result *v1alpha1.NodeRemediation, err error) {
	result = &v1alpha1.NodeRemediation{}
	err = c.client.Put().
		Resource("noderemediations").
		Name(nodeRemediation.Name).
		Body(nodeRemediation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *nodeRemediations) UpdateStatus(nodeRemediation *v1alpha1.NodeRemediation) (result *v1alpha1.NodeRemediation, err error) {
	result = &v1alpha1.NodeRemediation{}
	err = c.client.Put().
		Resource("noderemediations").
		Name(nodeRemediation.Name).
		SubResource("status").
		Body(nodeRemediation).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeRemediation and deletes it. Returns an error if one occurs.
func (c *nodeRemediations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("noderemediations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeRemediations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("noderemediations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeRemediation.
func (c *nodeRemediations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeRemediation, err error) {
	result = &v1alpha1.NodeRemediation{}
	err = c.client.Patch(pt).
		Resource("noderemediations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
